[Google]
template_month_file_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
template_year_file_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# 作成先フォルダ ID
destination_folder_id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[Notion]
database_id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
token = secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[Slack]
channel_id = xxxxxxxxxxx
token = xoxb-xxxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
